TARGET ?= usb_usb_rn42
CONFIG_H ?= config_rn42.h
RN42_ENABLE ?= yes
BTSTORE_ENABLE ?= no   # Support remote BT address store and restore
BATTERY_ENABLE ?= no   # Battery charger and monitor
include Makefile
